# Generated by Django 5.0 on 2023-12-29 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.userprofile')),
            ],
        ),
    ]
